### ISSUE TITLE
Kumano Kai Ni is missing from en-US.

### ISSUE THREAD

**Issue by printspike** [poooi/plugin-translator#12]
As the title said.
Kumano Carrier Kai Ni too.

**Comment by KagamiChan** [comment]
All ship translations come from http://kancolle.wikia.com/wiki/Ship_list, and the processing is automatic. Seems they're missing these 2 ships and I have no clue why

**Comment by printspike** [comment]
I see.
Apparently there is no one actively manage that page. The Iast 2 times I stumbled upon that page it wasn't updated as well so I had to add the info myself. No one just remembered to add Kumano Kai Ni I guess.

**Comment by printspike** [comment]
Added to the original page.

**Comment by KagamiChan** [comment]
@printspike Thanks, I'm releasing a new version.

**Comment by KagamiChan** [comment]
released
