### ISSUE TITLE
On getting data from KC Wikia

### ISSUE THREAD

**Issue by gakada** [poooi/plugin-translator#14]
Hello, I've noticed that this plugin gets its data from KC Wikia by parsing front-end pages. The core data is actually [stored](http://kancolle.wikia.com/wiki/Category:Data_modules) in a Lua backend, I have a script that uses MediaWiki API to enumerate those Lua pages and converts them to [JSON](https://github.com/gakada/kcdata/tree/master/wikia), so maybe that JSON can be used? Alternatively, there is also https://github.com/KC3Kai/kc3-translations.

**Comment by KagamiChan** [comment]
I did notice the existence of these data, but fetching them and executing them in lua vm is also complex. By far we only have some difficulties with enemy ship suffixes which could be monkey patched (but we're all doing the similar thing), so I'm not thinking of changing the code.

**Comment by gakada** [comment]
Well, I'm already converting all that Lua to JSON, the script if fairly simple (something like 100 lines of JS and 50 lines of Lua). I will see if I can generate JSON files just for names, identical to those used in this project, because right now some translations are missing (since some front-end pages are always behind).

Also, can the quests be translated? I see that if I just add translations in the file it somewhat conflicts with the quest plugin (it only adds some translations in tooltips).

**Comment by KagamiChan** [comment]
IMO since the wikia pages are generated from the backend database, the time lag between these two is not huge. The major factor here is the plugin publishing frequency

For quests we're using JSON structures to store the requirements and rewards, see [plugin-quest](https://github.com/poooi/plugin-quest)

**Comment by gakada** [comment]
It is usually not huge, except for (somewhat abandoned) enemy page, as it can take weeks (if not months) to update, like right now it was last updated in December.

I have plugin-quest installed, but it is

https://cdn.discordapp.com/attachments/176206906141048832/420335119463743498/u.png

(only English string here is one I added via this plugin).

**Comment by KagamiChan** [comment]
@gakada I realize you're mentioning quest name itself, since the quest name usually fails to imply what the quest is, I personally have no intention to translate them.

**Comment by gakada** [comment]
Yeah, in other viewers it is not exact translations, but quest codes (wikiwiki/etc.) and short descriptions, like on this screenshot, so you can see what it is without a tooltip.

**Comment by KagamiChan** [comment]
@gakada to add up the quest name translation could be too long to fit into the quest panel

**Comment by gakada** [comment]
Like, IMO `D2d1: Complete 3 Expe...` or `Complete 3 Expeditions` is better than just untranslated string.

**Comment by gakada** [comment]
Added `_names` files [here](https://github.com/gakada/kcdata/tree/master/wikia), those are from backend, so should be updated more frequently.

**Comment by gakada** [comment]
Just realized that some quests have same titles, so replacing those kanji in interface can't be done in this plugin anyway.

**Comment by gakada** [comment]
Still, running [this](https://gist.github.com/gakada/95d8e4d75925c6777200f80b6e4c6bdd) (have duplicates and missing many quests) gives
![u](https://user-images.githubusercontent.com/13043588/37061843-c64b750e-21a5-11e8-88f1-d38afb820df7.png)
