### ISSUE TITLE
Translation conflict for 16inch三連装砲

### ISSUE THREAD

**Issue by gakada** [poooi/plugin-translator#24]
There is actually two enemy equipment named `16inch三連装砲`, 509 and 568, they are differentiated in wikia translations, but it is not reflected here because only Japanese names are used for lookup.

Maybe `fetch` script should prefix such conflicts with `api_id`? But then it should be supported in the main program (e.g., lookup with `${api_id} ${api_name}`, then fallback to `api_name` lookup, then to `api_name`) and maybe other plugins.

Another similar case is quest titles (if they are going to be translated or interpreted in English), some quests have same titles.

**Comment by KagamiChan** [comment]
For `i18next`, we're now using `resources:16inch三連装砲` as key, and it will eventually fallback to `16inch三連装砲` if no entry matches in translations or if the plugin is not installed. There seems no easy way to work the extra lookup out without breaking the reading for non English users

**Comment by gakada** [comment]
Probably [contexts](https://www.i18next.com/translation-function/context) can be used. This plugin would provide for English:
```js
"16inch三連装砲_509": "16inch Triple Gun Mount",
"16inch三連装砲_568": "16inch Triple Gun Mount (Strong)",
"16inch連装砲": "16inch Twin Gun Mount",
// ...
```
Then for English it will be
```js
i18next.t('resources:16inch連装砲', { context: '508' })
// 16inch Twin Gun Mount
i18next.t('resources:16inch三連装砲', { context: '509' })
// 16inch Triple Gun Mount
i18next.t('resources:16inch三連装砲', { context: '568' })
// 16inch Triple Gun Mount (Strong)
```
For Japanese, respectively (assuming empty resources)
```js
// 16inch連装砲
// 16inch三連装砲
// 16inch三連装砲
```
etc. for other languages.

**Comment by KagamiChan** [comment]
awesome, I did not think of that

Would you like to file a PR on this?

**Comment by gakada** [comment]
Actually, that might be more useful as it applies to all enemies as well, like
```js
+  "空母ヲ級": "Standard Carrier Wo-Class (?)",
+  "空母ヲ級_1512": "Standard Carrier Wo-Class",
+  "空母ヲ級_1525": "Standard Carrier Wo-Class Elite",
+  "空母ヲ級_1528": "Standard Carrier Wo-Class Flagship",
+  "空母ヲ級_1579": "Standard Carrier Wo-Class Flagship II",
+  "空母ヲ級_1614": "Standard Carrier Wo-Class Flagship III",
+  "空母ヲ級_1615": "Standard Carrier Wo-Class Flagship IV",
+  "空母ヲ級改": "Standard Carrier Wo-Class Kai (?)",
+  "空母ヲ級改_1565": "Standard Carrier Wo-Class Kai Flagship",
+  "空母ヲ級改_1616": "Standard Carrier Wo-Class Kai Flagship II",
+  "空母ヲ級改_1617": "Standard Carrier Wo-Class Kai Flagship III",
+  "空母ヲ級改_1618": "Standard Carrier Wo-Class Kai Flagship IV",
+  "空母ヲ級改_1714": "Standard Carrier Wo-Class Kai Flagship V",
+  "空母ヲ級改_1715": "Standard Carrier Wo-Class Kai Flagship VI",
```
